{{- if .Values.ingress.enabled -}}
{{- $fullName := include "PLUGIN_NAME.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "PLUGIN_NAME.fullname" . }}-{{ .Values.environment.stage }}
  labels:
    app: {{ template "PLUGIN_NAME.name" . }}
    chart: {{ template "PLUGIN_NAME.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- if .Values.ingress.whitelist.ranges -}}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelist.ranges }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hostName }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "PLUGIN_NAME.fullname" . }}-{{ .Values.environment.stage }}
                port:
                  name: http
  tls: 
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
        - {{ .Values.ingress.hostName }}
{{- end }}
